// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  csSidebar: [
    {
      type: 'doc',
      id: 'cs/index',
      label: 'CS Overview',
    },
    {
      type: 'category',
      label: 'Reviewed Courses',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'cs/reviews'}],
    },
  ],
  mathSidebar: [
    {
      type: 'doc',
      id: 'math/index',
      label: 'Math Overview',
    },
  ],
  econSidebar: [
    {
      type: 'doc',
      id: 'econ/index',
      label: 'Econ Overview',
    },
  ],
};

export default sidebars;
